Repository ucsb-cs156-w22/team04-w22-5pm-HappyCows, pull requests merged in 2022-03, with the labels that each got.

#20 Update readme to include heroku deployments
  README.md
Labels: w22-5pm-4

#22 Profits
  frontend/package-lock.json
  frontend/package.json
  frontend/src/fixtures/profitsFixtures.js
  frontend/src/fixtures/profitsTableFixtures.js
  frontend/src/main/components/Commons/Profits.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/Profits.test.js
  frontend/src/tests/components/Commons/ProfitsTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Profit.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
Labels: w22-5pm-3, Attn-needs peer CR

#35 added Admin Display Table page and table component stub
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminDisplayTablePage.js
  frontend/src/tests/pages/AdminDisplayTablePage.test.js
Labels: w22-5pm-4

#28 W22 5pm 4 jz disable toast when not login, add two kinds of toast for user joining a common
  frontend/src/main/pages/HomePage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/pages/HomePage.test.js
  frontend/src/tests/utils/useBackend.test.js
Labels: w22-5pm-4

#41 Increase Controller Coverage
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UsersControllerTests.java
Labels: w22-5pm-3

#50 Increase Profits and ProfitsTable Mutation Coverage
  frontend/src/tests/components/Commons/Profits.test.js
  frontend/src/tests/components/Commons/ProfitsTable.test.js
Labels: w22-5pm-3

#33 W22 5pm 3 ig add images to play page
  frontend/src/index.css
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/PlayPage.js
Labels: w22-5pm-3, Merge-Candidate

#62 Remove moment.js Dependency
  frontend/package-lock.json
  frontend/package.json
  frontend/src/fixtures/profitsFixtures.js
  frontend/src/main/components/Commons/Profits.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/Profits.test.js
Labels: w22-5pm-3, 10

#61 Update gitignore to ignore mac and intellij files
  .gitignore
Labels: w22-5pm-3

#36 Admin Commons Table Component (GET)
  frontend/src/App.js
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/AdminCommonsTable.js
  frontend/src/main/components/Commons/CreateCommonsForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/OurTable.js
  frontend/src/main/pages/AdminCommonsTablePage.js
  frontend/src/main/pages/AdminDisplayTablePage.js
  frontend/src/main/utils/commonsUtils.js
  frontend/src/stories/components/Commons/AdminCommonsTable.stories.mdx
  frontend/src/tests/components/Commons/AdminCommonsTable.test.js
  frontend/src/tests/components/Commons/CreateCommonsForm.test.js
  frontend/src/tests/components/OurTable.test.js
  frontend/src/tests/pages/AdminCommonsTablePage.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/utils/commonsUtils.test.js
Labels: 10, w22-5pm-4

#58 w22 5pm 4 refresh on logout
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 10, w22-5pm-4

#72 w22 5pm 4 ay je - additional commons controller permissions tests
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-5pm-4, Merge-Candidate

#37 W22 5pm 4 jz delete common
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/main/components/Commons/AdminCommonsTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/stories/pages/AdminCommonsTablePage.stories.mdx
  frontend/src/tests/components/Commons/AdminCommonsTable.test.js
  frontend/src/tests/pages/HomePage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-5pm-4, Merge-Candidate

#56 changed common controller delete return JSON instead of string
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-5pm-4, Merge-Candidate

#70 W22 5pm 4 jz kd create edit common form for edit page
  frontend/src/main/components/Commons/AdminCommonsTable.js
  frontend/src/main/components/Commons/EditCommonsForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/stories/components/Commons/EditCommonsForm.stories.mdx
  frontend/src/stories/pages/AdminCommonsTablePage.stories.mdx
  frontend/src/tests/components/Commons/AdminCommonsTable.test.js
  frontend/src/tests/components/Commons/EditCommonsForm.test.js
  frontend/src/tests/pages/AdminCommonsTablePage.test.js
Labels: w22-5pm-4

#48 W22 5pm 3 rw,xh add `/buy` and `/sell` endpoints in userCommonsController
  .gitignore
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/UserCommonsTest.java
Labels: w22-5pm-3, Attn-please respond to CR, Merge-Candidate

#71 W22 5pm 4 jz sk kd AdminEditPage for edit commons
  .github/workflows/02-frontend-03-mutation-testing.yml
  frontend/src/App.js
  frontend/src/main/components/Commons/AdminCommonsTable.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/stories/pages/AdminEditCommonsPage.stories.mdx
  frontend/src/tests/pages/AdminCommonsTablePage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: w22-5pm-4, Merge-Candidate

#68 W22 5pm 3 ig commons overview backend: add endingDate variable
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-5pm-3, Merge-Candidate

#69 W22 5pm 3 ig add current day and endingDate to commons overview frontend
  .gitignore
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/components/Commons/CreateCommonsForm.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/components/Commons/CreateCommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
Labels: w22-5pm-3, Attn-needs peer CR

#73 W22 5pm 3 ng mw Add frontend to sell/buy cows, display total # of cows, and add the respective tests
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/pages/PlayPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: w22-5pm-3
